### ISSUE TITLE
python3 Bluetooth-Unlock.py commit errors !

### ISSUE THREAD

**Issue by wahbi** [LethalEthan/Bluetooth-Unlock#22]
**Describe the bug**
Python 3 has been detected you may continue

Traceback (most recent call last):
  File "Bluetooth-Unlock.py", line 33, in <module>
    config.read("config.ini")
  File "/usr/lib/python3.5/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/lib/python3.5/configparser.py", line 1063, in _read
    lineno)
configparser.DuplicateSectionError: While reading from 'config.ini' [line  3]: section 'VERSION' already exists

##

**Comment by LethalEthan** [comment]
If this is with the latest version, try deleting the config and replacing it with the one from github, i'll look into it.
