### ISSUE TITLE
Not working on Fedora 35 (5.14.16-301.fc35.x86_64)(GNOME 41.1)

### ISSUE THREAD

**Issue by Netherquark** [LethalEthan/Bluetooth-Unlock#30]
**Describe the bug**
Does not install on Fedora 35

**To Reproduce**
Steps to reproduce the behaviour:
1. Boot Fedora
2. Run install.sh
3. Run Bluetooth Unlock Python script

**Expected behaviour**
It works perfectly

**Screenshots**
![image](https://user-images.githubusercontent.com/65618735/141741430-a1d6d3f3-8bc4-4154-9317-240f66a5e70e.png)

**Desktop (please complete the following information):**
 - OS: Linux: Fedora 35
 - Version: BU-V1-Stable (latest commit)

**Additional context**
Also `pip install pybluez` results in the following:
```
2021-11-15T13:17:26,247 Using pip 21.2.3 from /usr/lib/python3.10/site-packages/pip (python 3.10)
2021-11-15T13:17:26,249 Defaulting to user installation because normal site-packages is not writeable
2021-11-15T13:17:26,266 Created temporary directory: /tmp/pip-ephem-wheel-cache-md7uopjo
2021-11-15T13:17:26,266 Created temporary directory: /tmp/pip-req-tracker-xt29vkoe
2021-11-15T13:17:26,266 Initialized build tracking at /tmp/pip-req-tracker-xt29vkoe
2021-11-15T13:17:26,266 Created build tracker: /tmp/pip-req-tracker-xt29vkoe
2021-11-15T13:17:26,266 Entered build tracker: /tmp/pip-req-tracker-xt29vkoe
2021-11-15T13:17:26,266 Created temporary directory: /tmp/pip-install-mnjkc5oq
2021-11-15T13:17:26,279 1 location(s) to search for versions of pybluez:
2021-11-15T13:17:26,279 * https://pypi.org/simple/pybluez/
2021-11-15T13:17:26,280 Fetching project page and analyzing links: https://pypi.org/simple/pybluez/
2021-11-15T13:17:26,281 Getting page https://pypi.org/simple/pybluez/
2021-11-15T13:17:26,281 Found index url https://pypi.org/simple
2021-11-15T13:17:26,452   Skipping link: unsupported archive format: .exe: https://files.pythonhosted.org/packages/0f/59/9ebd5c52831e2e37d628e40d2da3a86517df76388c8d5088e35f55a8f28f/PyBluez-0.20.win32-py2.7.exe#sha256=24d0db4b426179136d540f897ca2bc510b21898e31ffc2a2760849c12de29d8a (from https://pypi.org/simple/pybluez/)
2021-11-15T13:17:26,453   Skipping link: unsupported archive format: .exe: https://files.pythonhosted.org/packages/88/22/c6af0c15746ef8017c58d9cdd7b0de807a001392c51677ec82325b135fa4/PyBluez-0.20.win32-py3.1.exe#sha256=aca793b7b7621267643150f97204ea7bb9228c93b9222e620b5743af4ccb2cdf (from https://pypi.org/simple/pybluez/)
2021-11-15T13:17:26,453   Skipping link: unsupported archive format: .exe: https://files.pythonhosted.org/packages/c1/52/49e24a3e14711a931cf79d26a3e585c43aa605f8049bc7779d7eb6d45bdd/PyBluez-0.20.win32-py3.3.exe#sha256=be26651dd029aab60e7391deb142b3cee83a95d193bce29fe647418f7313586e (from https://pypi.org/simple/pybluez/)
2021-11-15T13:17:26,453   Skipping link: unsupported archive format: .exe: https://files.pythonhosted.org/packages/dd/e6/4ce2a1529b94db6118d05ef70f181a2ef1d0e1c20164386d4cd1ea6b05f2/PyBluez-0.20.win32-py3.4.exe#sha256=a9c990fd99c45ad9d93a8a20c062a36d644590fd1e6c33e9e431679e8d11649d (from https://pypi.org/simple/pybluez/)
2021-11-15T13:17:26,453   Found link https://files.pythonhosted.org/packages/05/92/c28bf15c336b444ced9bb994153fba2d5c6b603e49730801f10a49f0dee6/PyBluez-0.20.zip#sha256=8b7c1553027dc2c93140f26111b6c9ecac0b7c525eeb660c8f5fddc81652720d (from https://pypi.org/simple/pybluez/), version: 0.20
2021-11-15T13:17:26,453   Skipping link: unsupported archive format: .exe: https://files.pythonhosted.org/packages/bd/7d/07ea27d208d8ad23a29c4d53b6de5fc90a64c1cc763aef23ffb0df9c832f/PyBluez-0.21.win32-py2.7.exe#sha256=74058e5862c7a72d1642fd52f21bf891e1db8964c181719b4af328a36e404898 (from https://pypi.org/simple/pybluez/)
2021-11-15T13:17:26,453   Skipping link: unsupported archive format: .exe: https://files.pythonhosted.org/packages/02/68/490c6a7e11e1cb9aac1e2ea0d4766ee5371e7e9236a56aa935dad9a20cfc/PyBluez-0.21.win32-py3.3.exe#sha256=aef388a305d6edde0e90cc17cf1a3481bac654102de274db9e1b6f5e32127e4f (from https://pypi.org/simple/pybluez/)
2021-11-15T13:17:26,454   Skipping link: unsupported archive format: .exe: https://files.pythonhosted.org/packages/1f/93/ef3ef76a6302bdda2d54866e1c211fe12bf148f5e28eb51383c8a8a4f108/PyBluez-0.21.win32-py3.4.exe#sha256=d7af9fdbbdd771b2abb62ee7032fb4b4770365bd45451e2e9431866db20ee086 (from https://pypi.org/simple/pybluez/)
2021-11-15T13:17:26,454   Found link https://files.pythonhosted.org/packages/31/90/395b6e8c4e56f27747d268a768e8ecaf7ac1fc32cebd374b03ee56c415f4/PyBluez-0.21.zip#sha256=c10966bac1c62b025bb97a1141e6fc87adad8038ff2e5402ce5e9b5f1c0ebb91 (from https://pypi.org/simple/pybluez/), version: 0.21
2021-11-15T13:17:26,468   Skipping link: none of the wheel's tags (cp27-none-win32) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/bb/53/7b242af33321989c3568d11cf2764c52044c7fa97987b8b36f0a18fd87be/PyBluez-0.22-cp27-none-win32.whl#sha256=15f7deeedf1e1ef06be88a457e8cd69c61e6a621914b082f64644e20a58f8589 (from https://pypi.org/simple/pybluez/)
2021-11-15T13:17:26,469   Skipping link: none of the wheel's tags (cp34-none-win32) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/c2/94/3691e91c07e759a038b191f11f643a44da095608de287515b41d6858b52d/PyBluez-0.22-cp34-none-win32.whl#sha256=75009604b0923aec14e8dfa544e5713cb983fbfaa4af1646ae66234901de3979 (from https://pypi.org/simple/pybluez/)
2021-11-15T13:17:26,469   Skipping link: none of the wheel's tags (cp35-none-win32) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/50/ef/e77f66975a856a88bc73c01020c4111e5ecaa0c0242d41284eda77f286a3/PyBluez-0.22-cp35-none-win32.whl#sha256=5e2d602894c82291f677c6a8b1bd06fa140f0eaff7e9c4537537faa73df017f0 (from https://pypi.org/simple/pybluez/)
2021-11-15T13:17:26,469   Skipping link: unsupported archive format: .exe: https://files.pythonhosted.org/packages/dd/3b/2f6562867e822d862657ff4279ba5e668248670113eb0a71eef4b5948f1c/PyBluez-0.22.win32-py2.7.exe#sha256=7fd5f575d0faca67998f60b3cd4fcf03854a9a7d7798b35e325e324537db3173 (from https://pypi.org/simple/pybluez/)
2021-11-15T13:17:26,469   Skipping link: unsupported archive format: .exe: https://files.pythonhosted.org/packages/d1/fa/860b847dbda2ff37c12cde2c3ecab914726920baaf1a3e3968e537186381/PyBluez-0.22.win32-py3.4.exe#sha256=a0592aacfdd0f4deb58f010b14ffde7d44c36ade122f6506065416f2ee10647a (from https://pypi.org/simple/pybluez/)
2021-11-15T13:17:26,469   Found link https://files.pythonhosted.org/packages/c1/98/3149481d508bee174335be6725880f00d297afebe75c15e917af8f6fe169/PyBluez-0.22.zip#sha256=4ce006716a54d9d18e8186a3f1c8b12a8e6befecffe8fd5828a291fb694ce49d (from https://pypi.org/simple/pybluez/), version: 0.22
2021-11-15T13:17:26,469   Skipping link: none of the wheel's tags (cp27-cp27m-macosx_10_13_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/0b/e0/3528f46dc1867e53f927d7cd4af8dae17eadf651772c92e2330384155dcd/PyBluez-0.23-cp27-cp27m-macosx_10_13_x86_64.whl#sha256=7fe58ee9e53bc171d70907f5c5d3e47bc9ca4c0643dd7ca0f43ed388c916f3d4 (from https://pypi.org/simple/pybluez/)
2021-11-15T13:17:26,469   Skipping link: none of the wheel's tags (cp27-cp27m-win_amd64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/1c/d7/54d3d32f7f220efb9d50a2e7bf522fcce576d96e909b6210f01e23a517db/PyBluez-0.23-cp27-cp27m-win_amd64.whl#sha256=92abf92965261093e88c9d39353f3fc4d2997f5c9bd8c19fc23b1beb91e40e17 (from https://pypi.org/simple/pybluez/)
2021-11-15T13:17:26,470   Skipping link: none of the wheel's tags (cp35-cp35m-macosx_10_13_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/bb/42/d8fd9fad81eac543b4a9ed898cfd4eaedbd8784a79958aa8ef4a3d573774/PyBluez-0.23-cp35-cp35m-macosx_10_13_x86_64.whl#sha256=46a0c4cb39fb84c235ae7442363562575d11d7cca61b77ef035d832d15824bdd (from https://pypi.org/simple/pybluez/)
2021-11-15T13:17:26,470   Skipping link: none of the wheel's tags (cp35-cp35m-win_amd64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/db/c7/27a722931bfca928552a56b544c2bd1e2d6c2d54e0b981df19604f1b2102/PyBluez-0.23-cp35-cp35m-win_amd64.whl#sha256=493d8a184433efbe7965420b6933bca37d3cacdcd168905c56d3459a8c4a5834 (from https://pypi.org/simple/pybluez/)
2021-11-15T13:17:26,470   Skipping link: none of the wheel's tags (cp36-cp36m-macosx_10_13_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/bc/75/9f0cdf988ba5d21bc1cfa9a8432eac034f4586956e43980f4a660f99a7b3/PyBluez-0.23-cp36-cp36m-macosx_10_13_x86_64.whl#sha256=87499a2ebbd3a3a7d2e1b3286a4cdf05a5c8a51eb2a0503c51f7698334f44412 (from https://pypi.org/simple/pybluez/)
2021-11-15T13:17:26,470   Skipping link: none of the wheel's tags (cp36-cp36m-win_amd64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/11/76/7ad6c3f5af44e01f857f24fcb48b19f8f47d5c83b8be5870b12a111535a3/PyBluez-0.23-cp36-cp36m-win_amd64.whl#sha256=319dab31a15d10e4797a618deed5bafc3b1c074b3a9b6270d780b3ea7ed472d5 (from https://pypi.org/simple/pybluez/)
2021-11-15T13:17:26,470   Skipping link: none of the wheel's tags (cp37-cp37m-macosx_10_13_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/41/6f/108953aa521a1741e015add51ca7548602513f3da779e70b97c53b06b1c7/PyBluez-0.23-cp37-cp37m-macosx_10_13_x86_64.whl#sha256=22f5963e2ad6dfb7dddadb39ab29c3863bcd5335fbf324af948a2811c43f2455 (from https://pypi.org/simple/pybluez/)
2021-11-15T13:17:26,470   Skipping link: none of the wheel's tags (cp37-cp37m-win_amd64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/3e/78/d4ba3d69a20313be05afbea2ce5d29f7fa39f7a5c091fc7c1331a3feb3c1/PyBluez-0.23-cp37-cp37m-win_amd64.whl#sha256=578a2651fb48484cecd3e67c089daa53950223b5c0ee29113ff8900e49422aec (from https://pypi.org/simple/pybluez/)
2021-11-15T13:17:26,471   Found link https://files.pythonhosted.org/packages/08/9f/e9d93b266d2d1ea988780a52a696073ba0a65df65a532165fdf6ff90d0ed/PyBluez-0.23.tar.gz#sha256=c8f04d2e78951eaa9de486b4d49381704e8943d0a6e6e58f55fcd7b8582e90de (from https://pypi.org/simple/pybluez/), version: 0.23
2021-11-15T13:17:26,471 Skipping link: not a file: https://pypi.org/simple/pybluez/
2021-11-15T13:17:26,471 Given no hashes to check 4 links for project 'pybluez': discarding no candidates
2021-11-15T13:17:26,479 Collecting pybluez
2021-11-15T13:17:26,480   Created temporary directory: /tmp/pip-unpack-sy4k5bbv
2021-11-15T13:17:26,495   Using cached PyBluez-0.23.tar.gz (97 kB)
2021-11-15T13:17:26,535   Added pybluez from https://files.pythonhosted.org/packages/08/9f/e9d93b266d2d1ea988780a52a696073ba0a65df65a532165fdf6ff90d0ed/PyBluez-0.23.tar.gz#sha256=c8f04d2e78951eaa9de486b4d49381704e8943d0a6e6e58f55fcd7b8582e90de to build tracker '/tmp/pip-req-tracker-xt29vkoe'
2021-11-15T13:17:26,535     Running setup.py (path:/tmp/pip-install-mnjkc5oq/pybluez_91f441a6b0fd454cb56f76567af50a64/setup.py) egg_info for package pybluez
2021-11-15T13:17:26,535     Created temporary directory: /tmp/pip-pip-egg-info-rbh2qxuz
2021-11-15T13:17:26,536     Running command python setup.py egg_info
2021-11-15T13:17:26,987     running egg_info
2021-11-15T13:17:26,988     creating /tmp/pip-pip-egg-info-rbh2qxuz/PyBluez.egg-info
2021-11-15T13:17:26,988     writing /tmp/pip-pip-egg-info-rbh2qxuz/PyBluez.egg-info/PKG-INFO
2021-11-15T13:17:26,988     writing dependency_links to /tmp/pip-pip-egg-info-rbh2qxuz/PyBluez.egg-info/dependency_links.txt
2021-11-15T13:17:26,988     writing eager_resources to /tmp/pip-pip-egg-info-rbh2qxuz/PyBluez.egg-info/eager_resources.txt
2021-11-15T13:17:26,988     writing requirements to /tmp/pip-pip-egg-info-rbh2qxuz/PyBluez.egg-info/requires.txt
2021-11-15T13:17:26,988     writing top-level names to /tmp/pip-pip-egg-info-rbh2qxuz/PyBluez.egg-info/top_level.txt
2021-11-15T13:17:26,988     writing manifest file '/tmp/pip-pip-egg-info-rbh2qxuz/PyBluez.egg-info/SOURCES.txt'
2021-11-15T13:17:27,019     reading manifest file '/tmp/pip-pip-egg-info-rbh2qxuz/PyBluez.egg-info/SOURCES.txt'
2021-11-15T13:17:27,019     reading manifest template 'MANIFEST.in'
2021-11-15T13:17:27,019     warning: no files found matching 'README'
2021-11-15T13:17:27,022     warning: no files found matching '*.c' under directory 'macos'
2021-11-15T13:17:27,023     warning: no previously-included files matching '*.pyc' found under directory '*'
2021-11-15T13:17:27,023     warning: no previously-included files matching '*.o' found under directory '*'
2021-11-15T13:17:27,023     warning: no previously-included files matching '*.opp' found under directory '*'
2021-11-15T13:17:27,023     adding license file 'COPYING'
2021-11-15T13:17:27,024     writing manifest file '/tmp/pip-pip-egg-info-rbh2qxuz/PyBluez.egg-info/SOURCES.txt'
2021-11-15T13:17:27,059   Source in /tmp/pip-install-mnjkc5oq/pybluez_91f441a6b0fd454cb56f76567af50a64 has version 0.23, which satisfies requirement pybluez from https://files.pythonhosted.org/packages/08/9f/e9d93b266d2d1ea988780a52a696073ba0a65df65a532165fdf6ff90d0ed/PyBluez-0.23.tar.gz#sha256=c8f04d2e78951eaa9de486b4d49381704e8943d0a6e6e58f55fcd7b8582e90de
2021-11-15T13:17:27,059   Removed pybluez from https://files.pythonhosted.org/packages/08/9f/e9d93b266d2d1ea988780a52a696073ba0a65df65a532165fdf6ff90d0ed/PyBluez-0.23.tar.gz#sha256=c8f04d2e78951eaa9de486b4d49381704e8943d0a6e6e58f55fcd7b8582e90de from build tracker '/tmp/pip-req-tracker-xt29vkoe'
2021-11-15T13:17:27,062 Created temporary directory: /tmp/pip-unpack-ucxbc82d
2021-11-15T13:17:27,063 Using legacy 'setup.py install' for pybluez, since package 'wheel' is not installed.
2021-11-15T13:17:27,479 Installing collected packages: pybluez
2021-11-15T13:17:27,480   Created temporary directory: /tmp/pip-record-9ovpgkid
2021-11-15T13:17:27,481     Running command /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mnjkc5oq/pybluez_91f441a6b0fd454cb56f76567af50a64/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mnjkc5oq/pybluez_91f441a6b0fd454cb56f76567af50a64/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9ovpgkid/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/netherquark/.local/include/python3.10/pybluez
2021-11-15T13:17:27,834     running install
2021-11-15T13:17:27,834     running build
2021-11-15T13:17:27,835     running build_py
2021-11-15T13:17:27,848     creating build
2021-11-15T13:17:27,848     creating build/lib.linux-x86_64-3.10
2021-11-15T13:17:27,848     creating build/lib.linux-x86_64-3.10/bluetooth
2021-11-15T13:17:27,848     copying bluetooth/btcommon.py -> build/lib.linux-x86_64-3.10/bluetooth
2021-11-15T13:17:27,848     copying bluetooth/ble.py -> build/lib.linux-x86_64-3.10/bluetooth
2021-11-15T13:17:27,848     copying bluetooth/macos.py -> build/lib.linux-x86_64-3.10/bluetooth
2021-11-15T13:17:27,848     copying bluetooth/bluez.py -> build/lib.linux-x86_64-3.10/bluetooth
2021-11-15T13:17:27,848     copying bluetooth/widcomm.py -> build/lib.linux-x86_64-3.10/bluetooth
2021-11-15T13:17:27,849     copying bluetooth/msbt.py -> build/lib.linux-x86_64-3.10/bluetooth
2021-11-15T13:17:27,849     copying bluetooth/__init__.py -> build/lib.linux-x86_64-3.10/bluetooth
2021-11-15T13:17:27,849     /usr/lib/python3.10/site-packages/setuptools/lib2to3_ex.py:36: SetuptoolsDeprecationWarning: 2to3 support is deprecated. If the project still requires Python 2 support, please migrate to a single-codebase solution or employ an independent conversion process.
2021-11-15T13:17:27,849       warnings.warn(
2021-11-15T13:17:27,849     Fixing build/lib.linux-x86_64-3.10/bluetooth/btcommon.py build/lib.linux-x86_64-3.10/bluetooth/ble.py build/lib.linux-x86_64-3.10/bluetooth/macos.py build/lib.linux-x86_64-3.10/bluetooth/bluez.py build/lib.linux-x86_64-3.10/bluetooth/widcomm.py build/lib.linux-x86_64-3.10/bluetooth/msbt.py build/lib.linux-x86_64-3.10/bluetooth/__init__.py
2021-11-15T13:17:27,857     Skipping optional fixer: buffer
2021-11-15T13:17:27,880     Skipping optional fixer: idioms
2021-11-15T13:17:27,939     Skipping optional fixer: set_literal
2021-11-15T13:17:27,971     Skipping optional fixer: ws_comma
2021-11-15T13:17:28,627     Fixing build/lib.linux-x86_64-3.10/bluetooth/btcommon.py build/lib.linux-x86_64-3.10/bluetooth/ble.py build/lib.linux-x86_64-3.10/bluetooth/macos.py build/lib.linux-x86_64-3.10/bluetooth/bluez.py build/lib.linux-x86_64-3.10/bluetooth/widcomm.py build/lib.linux-x86_64-3.10/bluetooth/msbt.py build/lib.linux-x86_64-3.10/bluetooth/__init__.py
2021-11-15T13:17:28,630     Skipping optional fixer: buffer
2021-11-15T13:17:28,644     Skipping optional fixer: idioms
2021-11-15T13:17:28,751     Skipping optional fixer: set_literal
2021-11-15T13:17:28,776     Skipping optional fixer: ws_comma
2021-11-15T13:17:28,819     running build_ext
2021-11-15T13:17:28,822     building 'bluetooth._bluetooth' extension
2021-11-15T13:17:28,823     creating build/temp.linux-x86_64-3.10
2021-11-15T13:17:28,823     creating build/temp.linux-x86_64-3.10/bluez
2021-11-15T13:17:28,823     gcc -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I./port3 -I/usr/include/python3.10 -c bluez/btmodule.c -o build/temp.linux-x86_64-3.10/bluez/btmodule.o
2021-11-15T13:17:28,884     In file included from bluez/btmodule.c:20:
2021-11-15T13:17:28,885     bluez/btmodule.h:4:10: fatal error: Python.h: No such file or directory
2021-11-15T13:17:28,885         4 | #include "Python.h"
2021-11-15T13:17:28,885           |          ^~~~~~~~~~
2021-11-15T13:17:28,885     compilation terminated.
2021-11-15T13:17:28,888     error: command '/usr/bin/gcc' failed with exit code 1
2021-11-15T13:17:28,932 ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mnjkc5oq/pybluez_91f441a6b0fd454cb56f76567af50a64/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mnjkc5oq/pybluez_91f441a6b0fd454cb56f76567af50a64/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9ovpgkid/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/netherquark/.local/include/python3.10/pybluez Check the logs for full command output.
2021-11-15T13:17:28,933 Exception information:
2021-11-15T13:17:28,933 Traceback (most recent call last):
2021-11-15T13:17:28,933   File "/usr/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 783, in install
2021-11-15T13:17:28,933     success = install_legacy(
2021-11-15T13:17:28,933   File "/usr/lib/python3.10/site-packages/pip/_internal/operations/install/legacy.py", line 121, in install
2021-11-15T13:17:28,933     raise LegacyInstallFailure
2021-11-15T13:17:28,933 pip._internal.operations.install.legacy.LegacyInstallFailure
2021-11-15T13:17:28,933 
2021-11-15T13:17:28,933 During handling of the above exception, another exception occurred:
2021-11-15T13:17:28,933 
2021-11-15T13:17:28,933 Traceback (most recent call last):
2021-11-15T13:17:28,933   File "/usr/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
2021-11-15T13:17:28,933     status = self.run(options, args)
2021-11-15T13:17:28,933   File "/usr/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
2021-11-15T13:17:28,933     return func(self, options, args)
2021-11-15T13:17:28,933   File "/usr/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 390, in run
2021-11-15T13:17:28,933     installed = install_given_reqs(
2021-11-15T13:17:28,933   File "/usr/lib/python3.10/site-packages/pip/_internal/req/__init__.py", line 73, in install_given_reqs
2021-11-15T13:17:28,933     requirement.install(
2021-11-15T13:17:28,933   File "/usr/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 801, in install
2021-11-15T13:17:28,933     six.reraise(*exc.parent)
2021-11-15T13:17:28,933   File "/usr/lib/python3.10/site-packages/pip/_vendor/six.py", line 719, in reraise
2021-11-15T13:17:28,933     raise value
2021-11-15T13:17:28,933   File "/usr/lib/python3.10/site-packages/pip/_internal/operations/install/legacy.py", line 109, in install
2021-11-15T13:17:28,933     runner(
2021-11-15T13:17:28,933   File "/usr/lib/python3.10/site-packages/pip/_internal/utils/subprocess.py", line 274, in runner
2021-11-15T13:17:28,933     call_subprocess(
2021-11-15T13:17:28,933   File "/usr/lib/python3.10/site-packages/pip/_internal/utils/subprocess.py", line 244, in call_subprocess
2021-11-15T13:17:28,933     raise InstallationSubprocessError(proc.returncode, command_desc)
2021-11-15T13:17:28,933 pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mnjkc5oq/pybluez_91f441a6b0fd454cb56f76567af50a64/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mnjkc5oq/pybluez_91f441a6b0fd454cb56f76567af50a64/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9ovpgkid/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/netherquark/.local/include/python3.10/pybluez Check the logs for full command output.
2021-11-15T13:17:28,947 Removed build tracker: '/tmp/pip-req-tracker-xt29vkoe'
```

**Comment by LethalEthan** [comment]
Hi there, thank you for the information, for the bluez compile error iirc it's to do with not having python-dev package. As for adding support for the install I will not be doing that because V2 is in the pipeline and will make this whole process not needed 👍

**Comment by Netherquark** [comment]
Awesome looking forward to it

**Comment by CaptainMorgan12** [comment]
Hey @LethalEthan what python-dev package needs to be installed to make bluez compile?
